#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

LLVM_CONFIG = $(shell which llvm-config-19 2>/dev/null || which llvm-config 2>/dev/null)
ifneq ($(LLVM_CONFIG),)
LLVM_CFLAGS = $(shell $(LLVM_CONFIG) --cflags 2>/dev/null) -DXLANG_HAS_LLVM_JIT=1
LLVM_LDFLAGS = $(shell $(LLVM_CONFIG) --ldflags --libs orcjit executionengine core support native irreader analysis 2>/dev/null)
else
LLVM_CFLAGS = -DXLANG_HAS_LLVM_JIT=0
LLVM_LDFLAGS =
endif

INC =
CFLAGS = -Wall $(LLVM_CFLAGS)
RESINC =
#LIBDIR = -Lpcre/.libs
LIB =
LDFLAGS = -rdynamic $(LLVM_LDFLAGS) -L. -Wl,-Bstatic -lpcre -Wl,-Bdynamic -lm

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG =
OUT_DEBUG = bin/Debug/xlang

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE =
OUT_RELEASE = bin/Release/xlang

OBJ_DEBUG = $(OBJDIR_DEBUG)/xlang.o $(OBJDIR_DEBUG)/var_stack.o $(OBJDIR_DEBUG)/type_stack.o $(OBJDIR_DEBUG)/lexer.o $(OBJDIR_DEBUG)/md5.o $(OBJDIR_DEBUG)/functions.o $(OBJDIR_DEBUG)/func_stack.o $(OBJDIR_DEBUG)/echo.o $(OBJDIR_DEBUG)/xsocket.o $(OBJDIR_DEBUG)/xfile.o $(OBJDIR_DEBUG)/xsys.o $(OBJDIR_DEBUG)/xstring.o $(OBJDIR_DEBUG)/xmath.o $(OBJDIR_DEBUG)/xcollection.o $(OBJDIR_DEBUG)/ximport.o $(OBJDIR_DEBUG)/xgc.o $(OBJDIR_DEBUG)/xdiag.o $(OBJDIR_DEBUG)/xdatetime.o $(OBJDIR_DEBUG)/xjson.o $(OBJDIR_DEBUG)/xast.o $(OBJDIR_DEBUG)/xast_parser.o $(OBJDIR_DEBUG)/xir.o $(OBJDIR_DEBUG)/xir_compiler.o $(OBJDIR_DEBUG)/xvm.o $(OBJDIR_DEBUG)/arena.o $(OBJDIR_DEBUG)/xdis_html.o $(OBJDIR_DEBUG)/xllvm_emit.o $(OBJDIR_DEBUG)/xllvm_rt.o $(OBJDIR_DEBUG)/xllvm_jit.o
OBJ_RELEASE = $(OBJDIR_RELEASE)/xlang.o $(OBJDIR_RELEASE)/var_stack.o $(OBJDIR_RELEASE)/type_stack.o $(OBJDIR_RELEASE)/lexer.o $(OBJDIR_RELEASE)/md5.o $(OBJDIR_RELEASE)/functions.o $(OBJDIR_RELEASE)/func_stack.o $(OBJDIR_RELEASE)/echo.o $(OBJDIR_RELEASE)/xsocket.o $(OBJDIR_RELEASE)/xfile.o $(OBJDIR_RELEASE)/xsys.o $(OBJDIR_RELEASE)/xstring.o $(OBJDIR_RELEASE)/xmath.o $(OBJDIR_RELEASE)/xcollection.o $(OBJDIR_RELEASE)/ximport.o $(OBJDIR_RELEASE)/xgc.o $(OBJDIR_RELEASE)/xdiag.o $(OBJDIR_RELEASE)/xdatetime.o $(OBJDIR_RELEASE)/xjson.o $(OBJDIR_RELEASE)/xast.o $(OBJDIR_RELEASE)/xast_parser.o $(OBJDIR_RELEASE)/xir.o $(OBJDIR_RELEASE)/xir_compiler.o $(OBJDIR_RELEASE)/xvm.o $(OBJDIR_RELEASE)/arena.o $(OBJDIR_RELEASE)/xdis_html.o $(OBJDIR_RELEASE)/xllvm_emit.o $(OBJDIR_RELEASE)/xllvm_rt.o $(OBJDIR_RELEASE)/xllvm_jit.o

all: debug release

clean: clean_debug clean_release

before_debug:
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: $(OBJDIR_DEBUG)/xllvm_rt.o
	cp -f $(OBJDIR_DEBUG)/xllvm_rt.o bin/Debug/xllvm_rt.o

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/xlang.o: xlang.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xlang.c -o $(OBJDIR_DEBUG)/xlang.o

$(OBJDIR_DEBUG)/var_stack.o: var_stack.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c var_stack.c -o $(OBJDIR_DEBUG)/var_stack.o

$(OBJDIR_DEBUG)/type_stack.o: type_stack.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c type_stack.c -o $(OBJDIR_DEBUG)/type_stack.o

$(OBJDIR_DEBUG)/md5.o: md5.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c md5.c -o $(OBJDIR_DEBUG)/md5.o

#$(OBJDIR_DEBUG)/http.o: http.c
#	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c http.c -o $(OBJDIR_DEBUG)/http.o

$(OBJDIR_DEBUG)/functions.o: functions.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c functions.c -o $(OBJDIR_DEBUG)/functions.o

$(OBJDIR_DEBUG)/func_stack.o: func_stack.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c func_stack.c -o $(OBJDIR_DEBUG)/func_stack.o

$(OBJDIR_DEBUG)/echo.o: echo.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c echo.c -o $(OBJDIR_DEBUG)/echo.o

$(OBJDIR_DEBUG)/xsocket.o: xsocket.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xsocket.c -o $(OBJDIR_DEBUG)/xsocket.o

$(OBJDIR_DEBUG)/xfile.o: xfile.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xfile.c -o $(OBJDIR_DEBUG)/xfile.o

$(OBJDIR_DEBUG)/xsys.o: xsys.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xsys.c -o $(OBJDIR_DEBUG)/xsys.o

$(OBJDIR_DEBUG)/xstring.o: xstring.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xstring.c -o $(OBJDIR_DEBUG)/xstring.o

$(OBJDIR_DEBUG)/xmath.o: xmath.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xmath.c -o $(OBJDIR_DEBUG)/xmath.o

$(OBJDIR_DEBUG)/xcollection.o: xcollection.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xcollection.c -o $(OBJDIR_DEBUG)/xcollection.o

$(OBJDIR_DEBUG)/ximport.o: ximport.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ximport.c -o $(OBJDIR_DEBUG)/ximport.o

$(OBJDIR_DEBUG)/xgc.o: xgc.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xgc.c -o $(OBJDIR_DEBUG)/xgc.o

$(OBJDIR_DEBUG)/lexer.o: lexer.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lexer.c -o $(OBJDIR_DEBUG)/lexer.o

$(OBJDIR_DEBUG)/xdiag.o: xdiag.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xdiag.c -o $(OBJDIR_DEBUG)/xdiag.o

$(OBJDIR_DEBUG)/xdatetime.o: xdatetime.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xdatetime.c -o $(OBJDIR_DEBUG)/xdatetime.o

$(OBJDIR_DEBUG)/xjson.o: xjson.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xjson.c -o $(OBJDIR_DEBUG)/xjson.o

$(OBJDIR_DEBUG)/xast.o: xast.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xast.c -o $(OBJDIR_DEBUG)/xast.o

$(OBJDIR_DEBUG)/xast_parser.o: xast_parser.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xast_parser.c -o $(OBJDIR_DEBUG)/xast_parser.o

$(OBJDIR_DEBUG)/xir.o: xir.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xir.c -o $(OBJDIR_DEBUG)/xir.o

$(OBJDIR_DEBUG)/xir_compiler.o: xir_compiler.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xir_compiler.c -o $(OBJDIR_DEBUG)/xir_compiler.o

$(OBJDIR_DEBUG)/xvm.o: xvm.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xvm.c -o $(OBJDIR_DEBUG)/xvm.o

$(OBJDIR_DEBUG)/arena.o: arena.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c arena.c -o $(OBJDIR_DEBUG)/arena.o

$(OBJDIR_DEBUG)/xdis_html.o: xdis_html.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xdis_html.c -o $(OBJDIR_DEBUG)/xdis_html.o

$(OBJDIR_DEBUG)/xllvm_emit.o: xllvm_emit.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xllvm_emit.c -o $(OBJDIR_DEBUG)/xllvm_emit.o

$(OBJDIR_DEBUG)/xllvm_rt.o: xllvm_rt.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xllvm_rt.c -o $(OBJDIR_DEBUG)/xllvm_rt.o

$(OBJDIR_DEBUG)/xllvm_jit.o: xllvm_jit.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xllvm_jit.c -o $(OBJDIR_DEBUG)/xllvm_jit.o

clean_debug:
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release:
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: $(OBJDIR_RELEASE)/xllvm_rt.o
	cp -f $(OBJDIR_RELEASE)/xllvm_rt.o bin/Release/xllvm_rt.o

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/xlang.o: xlang.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xlang.c -o $(OBJDIR_RELEASE)/xlang.o

$(OBJDIR_RELEASE)/var_stack.o: var_stack.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c var_stack.c -o $(OBJDIR_RELEASE)/var_stack.o

$(OBJDIR_RELEASE)/type_stack.o: type_stack.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c type_stack.c -o $(OBJDIR_RELEASE)/type_stack.o

$(OBJDIR_RELEASE)/md5.o: md5.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c md5.c -o $(OBJDIR_RELEASE)/md5.o

#$(OBJDIR_RELEASE)/http.o: http.c
#	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c http.c -o $(OBJDIR_RELEASE)/http.o

$(OBJDIR_RELEASE)/functions.o: functions.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c functions.c -o $(OBJDIR_RELEASE)/functions.o

$(OBJDIR_RELEASE)/func_stack.o: func_stack.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c func_stack.c -o $(OBJDIR_RELEASE)/func_stack.o

$(OBJDIR_RELEASE)/echo.o: echo.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c echo.c -o $(OBJDIR_RELEASE)/echo.o

$(OBJDIR_RELEASE)/xsocket.o: xsocket.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xsocket.c -o $(OBJDIR_RELEASE)/xsocket.o
$(OBJDIR_RELEASE)/xfile.o: xfile.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xfile.c -o $(OBJDIR_RELEASE)/xfile.o

$(OBJDIR_RELEASE)/xsys.o: xsys.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xsys.c -o $(OBJDIR_RELEASE)/xsys.o

$(OBJDIR_RELEASE)/xstring.o: xstring.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xstring.c -o $(OBJDIR_RELEASE)/xstring.o

$(OBJDIR_RELEASE)/xmath.o: xmath.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xmath.c -o $(OBJDIR_RELEASE)/xmath.o

$(OBJDIR_RELEASE)/xcollection.o: xcollection.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xcollection.c -o $(OBJDIR_RELEASE)/xcollection.o

$(OBJDIR_RELEASE)/ximport.o: ximport.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ximport.c -o $(OBJDIR_RELEASE)/ximport.o

$(OBJDIR_RELEASE)/xgc.o: xgc.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xgc.c -o $(OBJDIR_RELEASE)/xgc.o

$(OBJDIR_RELEASE)/lexer.o: lexer.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lexer.c -o $(OBJDIR_RELEASE)/lexer.o

$(OBJDIR_RELEASE)/xdiag.o: xdiag.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xdiag.c -o $(OBJDIR_RELEASE)/xdiag.o

$(OBJDIR_RELEASE)/xdatetime.o: xdatetime.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xdatetime.c -o $(OBJDIR_RELEASE)/xdatetime.o

$(OBJDIR_RELEASE)/xjson.o: xjson.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xjson.c -o $(OBJDIR_RELEASE)/xjson.o

$(OBJDIR_RELEASE)/xast.o: xast.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xast.c -o $(OBJDIR_RELEASE)/xast.o

$(OBJDIR_RELEASE)/xast_parser.o: xast_parser.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xast_parser.c -o $(OBJDIR_RELEASE)/xast_parser.o

$(OBJDIR_RELEASE)/xir.o: xir.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xir.c -o $(OBJDIR_RELEASE)/xir.o

$(OBJDIR_RELEASE)/xir_compiler.o: xir_compiler.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xir_compiler.c -o $(OBJDIR_RELEASE)/xir_compiler.o

$(OBJDIR_RELEASE)/xvm.o: xvm.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xvm.c -o $(OBJDIR_RELEASE)/xvm.o

$(OBJDIR_RELEASE)/arena.o: arena.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c arena.c -o $(OBJDIR_RELEASE)/arena.o

$(OBJDIR_RELEASE)/xdis_html.o: xdis_html.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xdis_html.c -o $(OBJDIR_RELEASE)/xdis_html.o

$(OBJDIR_RELEASE)/xllvm_emit.o: xllvm_emit.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xllvm_emit.c -o $(OBJDIR_RELEASE)/xllvm_emit.o

$(OBJDIR_RELEASE)/xllvm_rt.o: xllvm_rt.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xllvm_rt.c -o $(OBJDIR_RELEASE)/xllvm_rt.o

$(OBJDIR_RELEASE)/xllvm_jit.o: xllvm_jit.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xllvm_jit.c -o $(OBJDIR_RELEASE)/xllvm_jit.o

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release
