#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =
CFLAGS = -Wall
RESINC =
#LIBDIR = -Lpcre/.libs
LIB =
LDFLAGS = -L. -Wl,-Bstatic -lpcre -Wl,-Bdynamic -lm

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG =
OUT_DEBUG = bin/Debug/xlang

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE =
OUT_RELEASE = bin/Release/xlang

OBJ_DEBUG = $(OBJDIR_DEBUG)/calc.o $(OBJDIR_DEBUG)/xlang.o $(OBJDIR_DEBUG)/var_stack.o $(OBJDIR_DEBUG)/type_stack.o $(OBJDIR_DEBUG)/stack.o $(OBJDIR_DEBUG)/save.o $(OBJDIR_DEBUG)/compile.o $(OBJDIR_DEBUG)/parse.o $(OBJDIR_DEBUG)/lexer.o $(OBJDIR_DEBUG)/md5.o $(OBJDIR_DEBUG)/functions.o $(OBJDIR_DEBUG)/func_stack.o $(OBJDIR_DEBUG)/debuge.o $(OBJDIR_DEBUG)/echo.o $(OBJDIR_DEBUG)/xsocket.o $(OBJDIR_DEBUG)/xfile.o $(OBJDIR_DEBUG)/xsys.o $(OBJDIR_DEBUG)/xstring.o $(OBJDIR_DEBUG)/xmath.o $(OBJDIR_DEBUG)/xcollection.o $(OBJDIR_DEBUG)/ximport.o $(OBJDIR_DEBUG)/xgc.o $(OBJDIR_DEBUG)/xdiag.o $(OBJDIR_DEBUG)/xdatetime.o $(OBJDIR_DEBUG)/xjson.o #$(OBJDIR_DEBUG)/http.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/calc.o $(OBJDIR_RELEASE)/xlang.o $(OBJDIR_RELEASE)/var_stack.o $(OBJDIR_RELEASE)/type_stack.o $(OBJDIR_RELEASE)/stack.o $(OBJDIR_RELEASE)/save.o $(OBJDIR_RELEASE)/compile.o $(OBJDIR_RELEASE)/parse.o $(OBJDIR_RELEASE)/lexer.o $(OBJDIR_RELEASE)/md5.o $(OBJDIR_RELEASE)/functions.o $(OBJDIR_RELEASE)/func_stack.o $(OBJDIR_RELEASE)/debuge.o $(OBJDIR_RELEASE)/echo.o $(OBJDIR_RELEASE)/xsocket.o $(OBJDIR_RELEASE)/xfile.o $(OBJDIR_RELEASE)/xsys.o $(OBJDIR_RELEASE)/xstring.o $(OBJDIR_RELEASE)/xmath.o $(OBJDIR_RELEASE)/xcollection.o $(OBJDIR_RELEASE)/ximport.o $(OBJDIR_RELEASE)/xgc.o $(OBJDIR_RELEASE)/xdiag.o $(OBJDIR_RELEASE)/xdatetime.o $(OBJDIR_RELEASE)/xjson.o #$(OBJDIR_RELEASE)/http.o

all: debug release

clean: clean_debug clean_release

before_debug:
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug:

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/xlang.o: xlang.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xlang.c -o $(OBJDIR_DEBUG)/xlang.o

$(OBJDIR_DEBUG)/var_stack.o: var_stack.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c var_stack.c -o $(OBJDIR_DEBUG)/var_stack.o

$(OBJDIR_DEBUG)/type_stack.o: type_stack.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c type_stack.c -o $(OBJDIR_DEBUG)/type_stack.o

$(OBJDIR_DEBUG)/stack.o: stack.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c stack.c -o $(OBJDIR_DEBUG)/stack.o

$(OBJDIR_DEBUG)/save.o: save.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c save.c -o $(OBJDIR_DEBUG)/save.o

$(OBJDIR_DEBUG)/compile.o: compile.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c compile.c -o $(OBJDIR_DEBUG)/compile.o

$(OBJDIR_DEBUG)/parse.o: parse.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c parse.c -o $(OBJDIR_DEBUG)/parse.o

$(OBJDIR_DEBUG)/md5.o: md5.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c md5.c -o $(OBJDIR_DEBUG)/md5.o

#$(OBJDIR_DEBUG)/http.o: http.c
#	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c http.c -o $(OBJDIR_DEBUG)/http.o

$(OBJDIR_DEBUG)/functions.o: functions.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c functions.c -o $(OBJDIR_DEBUG)/functions.o

$(OBJDIR_DEBUG)/calc.o: calc.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c calc.c -o $(OBJDIR_DEBUG)/calc.o

$(OBJDIR_DEBUG)/func_stack.o: func_stack.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c func_stack.c -o $(OBJDIR_DEBUG)/func_stack.o

$(OBJDIR_DEBUG)/debuge.o: debuge.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c debuge.c -o $(OBJDIR_DEBUG)/debuge.o

$(OBJDIR_DEBUG)/echo.o: echo.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c echo.c -o $(OBJDIR_DEBUG)/echo.o

$(OBJDIR_DEBUG)/xsocket.o: xsocket.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xsocket.c -o $(OBJDIR_DEBUG)/xsocket.o

$(OBJDIR_DEBUG)/xfile.o: xfile.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xfile.c -o $(OBJDIR_DEBUG)/xfile.o

$(OBJDIR_DEBUG)/xsys.o: xsys.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xsys.c -o $(OBJDIR_DEBUG)/xsys.o

$(OBJDIR_DEBUG)/xstring.o: xstring.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xstring.c -o $(OBJDIR_DEBUG)/xstring.o

$(OBJDIR_DEBUG)/xmath.o: xmath.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xmath.c -o $(OBJDIR_DEBUG)/xmath.o

$(OBJDIR_DEBUG)/xcollection.o: xcollection.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xcollection.c -o $(OBJDIR_DEBUG)/xcollection.o

$(OBJDIR_DEBUG)/ximport.o: ximport.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ximport.c -o $(OBJDIR_DEBUG)/ximport.o

$(OBJDIR_DEBUG)/xgc.o: xgc.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xgc.c -o $(OBJDIR_DEBUG)/xgc.o

$(OBJDIR_DEBUG)/lexer.o: lexer.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lexer.c -o $(OBJDIR_DEBUG)/lexer.o

$(OBJDIR_DEBUG)/xdiag.o: xdiag.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xdiag.c -o $(OBJDIR_DEBUG)/xdiag.o

$(OBJDIR_DEBUG)/xdatetime.o: xdatetime.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xdatetime.c -o $(OBJDIR_DEBUG)/xdatetime.o

$(OBJDIR_DEBUG)/xjson.o: xjson.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xjson.c -o $(OBJDIR_DEBUG)/xjson.o

clean_debug:
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release:
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release:

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/xlang.o: xlang.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xlang.c -o $(OBJDIR_RELEASE)/xlang.o

$(OBJDIR_RELEASE)/var_stack.o: var_stack.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c var_stack.c -o $(OBJDIR_RELEASE)/var_stack.o

$(OBJDIR_RELEASE)/type_stack.o: type_stack.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c type_stack.c -o $(OBJDIR_RELEASE)/type_stack.o

$(OBJDIR_RELEASE)/stack.o: stack.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c stack.c -o $(OBJDIR_RELEASE)/stack.o

$(OBJDIR_RELEASE)/save.o: save.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c save.c -o $(OBJDIR_RELEASE)/save.o

$(OBJDIR_RELEASE)/compile.o: compile.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c compile.c -o $(OBJDIR_RELEASE)/compile.o

$(OBJDIR_RELEASE)/parse.o: parse.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c parse.c -o $(OBJDIR_RELEASE)/parse.o

$(OBJDIR_RELEASE)/md5.o: md5.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c md5.c -o $(OBJDIR_RELEASE)/md5.o

#$(OBJDIR_RELEASE)/http.o: http.c
#	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c http.c -o $(OBJDIR_RELEASE)/http.o

$(OBJDIR_RELEASE)/functions.o: functions.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c functions.c -o $(OBJDIR_RELEASE)/functions.o

$(OBJDIR_RELEASE)/calc.o: calc.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c calc.c -o $(OBJDIR_RELEASE)/calc.o

$(OBJDIR_RELEASE)/func_stack.o: func_stack.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c func_stack.c -o $(OBJDIR_RELEASE)/func_stack.o

$(OBJDIR_RELEASE)/debuge.o: debuge.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c debuge.c -o $(OBJDIR_RELEASE)/debuge.o

$(OBJDIR_RELEASE)/echo.o: echo.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c echo.c -o $(OBJDIR_RELEASE)/echo.o

$(OBJDIR_RELEASE)/xsocket.o: xsocket.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xsocket.c -o $(OBJDIR_RELEASE)/xsocket.o
$(OBJDIR_RELEASE)/xfile.o: xfile.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xfile.c -o $(OBJDIR_RELEASE)/xfile.o

$(OBJDIR_RELEASE)/xsys.o: xsys.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xsys.c -o $(OBJDIR_RELEASE)/xsys.o

$(OBJDIR_RELEASE)/xstring.o: xstring.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xstring.c -o $(OBJDIR_RELEASE)/xstring.o

$(OBJDIR_RELEASE)/xmath.o: xmath.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xmath.c -o $(OBJDIR_RELEASE)/xmath.o

$(OBJDIR_RELEASE)/xcollection.o: xcollection.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xcollection.c -o $(OBJDIR_RELEASE)/xcollection.o

$(OBJDIR_RELEASE)/ximport.o: ximport.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ximport.c -o $(OBJDIR_RELEASE)/ximport.o

$(OBJDIR_RELEASE)/xgc.o: xgc.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xgc.c -o $(OBJDIR_RELEASE)/xgc.o

$(OBJDIR_RELEASE)/lexer.o: lexer.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lexer.c -o $(OBJDIR_RELEASE)/lexer.o

$(OBJDIR_RELEASE)/xdiag.o: xdiag.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xdiag.c -o $(OBJDIR_RELEASE)/xdiag.o

$(OBJDIR_RELEASE)/xdatetime.o: xdatetime.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xdatetime.c -o $(OBJDIR_RELEASE)/xdatetime.o

$(OBJDIR_RELEASE)/xjson.o: xjson.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xjson.c -o $(OBJDIR_RELEASE)/xjson.o

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release
